### ISSUE TITLE
FQDN Incorrectly Determined to be "localhost" on OS X

### ISSUE THREAD

**Issue by DracoAter** [opscode/ohai#457]
Hello,

Didn't find anything concerning this bug https://tickets.opscode.com/browse/OHAI-585
Still takes place in 7.4.0.

**Comment by lamont-granquist** [comment]
You need to use `node['machinename']` not `node['fqdn']`.  fqdn is defined to be the resolved FQDN via DNS lookups (`hostname -f` in linux) while the machinename is just the configured hostname.
